networks:
  mongodb:
    name: rover-net

services:
  marsrover:
    container_name: marsrover
    build: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ~/docker/marsrover/persistent-data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongodb