networks:
  mongodb:

services:
  marsrover:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mongodb
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - ~/marsrover/persistent-data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongodb